plugins { id 'com.android.application' }

android {
    namespace 'com.wngrlhnn.swfarcade'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wngrlhnn.swfarcade'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
